<section>

    <h2>Définitions</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod, neque in officiis dignissimos quisquam odio vero nam nihil aspernatur culpa, pariatur dicta. Ipsam odit eaque, magnam molestias quis ab ex sit porro, ipsum sapiente alias dolores maiores officia repellat sed asperiores. Delectus pariatur harum ut vel officiis minus odio vero?</p>
    <p>Nobis quo, inventore impedit officia praesentium non consectetur pariatur quaerat temporibus eaque minus totam qui quos eius dolore hic quidem? Ullam iste qui dolorem alias numquam a, corrupti non commodi necessitatibus repellat nisi vel corporis asperiores voluptas quos saepe iure maiores ratione impedit labore. Ratione deserunt cum explicabo porro qui?</p>
    <p>Voluptatem ullam quisquam blanditiis quam doloribus minus praesentium pariatur, quasi eum sunt est impedit porro vitae natus, veritatis optio iusto non aliquid! Fugit maxime maiores inventore blanditiis, molestias beatae deleniti voluptate nemo odio eius labore eligendi nisi fuga doloribus nam consectetur tenetur eum impedit dolorem error, facilis soluta ipsam? Praesentium?</p>
    <p>A architecto temporibus cupiditate exercitationem aliquid illum, vitae odio dignissimos, earum officiis provident optio fugiat autem eum dolore quisquam, enim unde fuga aperiam quibusdam. Debitis incidunt, temporibus accusamus suscipit iste ipsum ratione dolorum repellat quidem iusto expedita corporis assumenda itaque consectetur, amet est aspernatur nemo similique quisquam maiores tempore provident?</p>
    <p>Eum quos, aspernatur itaque accusamus molestias fugit. Dolorum sit, voluptate autem exercitationem molestiae at quae. Amet, id! Provident corrupti, expedita dolore iure error minus, hic, velit ratione nostrum deserunt doloremque. Placeat ipsam accusantium aspernatur? Modi vitae tempora sint facilis impedit molestias aut necessitatibus non, natus quisquam similique libero pariatur reiciendis?</p>
    <p>Sapiente minus ad quo iure aliquid earum animi placeat expedita. Quas explicabo porro culpa officiis nemo. Labore similique quas eum, animi soluta voluptatem, beatae vitae unde porro fugiat odit sapiente in, neque officiis error cum eveniet hic ut? Soluta, non at nemo ducimus sed aperiam dicta voluptatibus praesentium voluptas perspiciatis.</p>
    <p>Fugiat, itaque impedit at excepturi voluptates ipsam cumque? Sunt libero eligendi, saepe molestiae qui soluta veniam necessitatibus quam? Sequi veniam optio saepe neque suscipit velit, nihil voluptas soluta! Accusamus quasi ad deserunt quibusdam sit. Officiis, nostrum quas aliquam eveniet eligendi iste porro maiores soluta tenetur, beatae fugit, dolor laboriosam dicta.</p>
    <p>Laudantium ad natus excepturi reiciendis laboriosam quod exercitationem ex quisquam, maiores ullam. Odit harum facilis perspiciatis nobis, impedit sequi obcaecati blanditiis corporis natus? Rerum, quaerat asperiores totam praesentium cupiditate repellat quo? At molestias, accusantium eveniet sed debitis numquam, illo nihil aut quia fuga maxime omnis impedit molestiae delectus nulla. Praesentium.</p>
    <p>Adipisci, facere voluptates! Sed error inventore voluptatum incidunt rerum cum fugiat exercitationem sequi quaerat nam labore, similique, delectus dignissimos nihil, temporibus quos blanditiis numquam. Laboriosam libero dolores architecto amet quidem necessitatibus porro odit voluptatibus sint eveniet eius mollitia velit fugiat quo ipsam at, rerum vel est perferendis repudiandae tempore! Veritatis.</p>
    <p>Excepturi nulla atque eos a debitis ex accusamus asperiores corrupti iusto molestias, eaque vel soluta necessitatibus doloremque rem sint ab nostrum? Quia fugit iure amet blanditiis voluptate nulla nemo dolorem tempora? Nisi, eveniet? Aspernatur assumenda obcaecati ullam, error inventore debitis amet deleniti minus odit dolorem facere dolores ipsum vitae veritatis.</p>

</section>